spring.application.name=transaction-lab

spring.datasource.url=jdbc:postgresql://localhost:5432/transactional_lab
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true